#!/bin/bash

mode=$1

case $mode in
    speakers)
      amixer -c0 sset Speaker unmute
      amixer -c0 sset "Bass Speaker" unmute
      amixer -c0 sset Headphone mute
      pactl unload-module module-combine-sink
        ;;
    jack)
      amixer -c0 sset Speaker mute
      amixer -c0 sset "Bass Speaker" mute
      amixer -c0 sset Headphone unmute
      pactl unload-module module-combine-sink
        ;;
    headphones)
        audio jack
        pactl load-module module-combine-sink
        pactl set-default-sink combined
        ;;
    *)
        echo "usage: $(basename "$0") [ speakers | jack | headphones ]";
        exit 1;;
esac
