#!/usr/bin/env bash
set -euo pipefail

function init_env() {
    export DISPLAY=${DISPLAY:-":0"}
    export XAUTHORITY=${XAUTHORITY:-$(
        find /home/*/.Xauthority -print -quit
    )}
}

function parse_xinput_devices() {
  local REGEX="↳ (.*[^ ]) *	id=([0-9]*).*\[(master|slave) +([a-z]+) \(([0-9]+)\)\]"

  while read -r line; do
      [[ "$line" =~ $REGEX ]] || continue
      local name=${BASH_REMATCH[1]}
      local id=${BASH_REMATCH[2]}
      local type=${BASH_REMATCH[4]}

      echo "$type" "$id" "$name"
  done <<<"$(xinput list)"
}

function apply_keymap() {
    local id=$1
    local name=$2
    local args=()

    case "$name" in
        'HID 046a:0011' | \
        'Cypress  PS2toUSB KBM Bridge V2.02a' | \
        'Logitech USB Keyboard')
            args=(
                '-layout' 'ch'
            )
            ;;
        'Apple SPI Keyboard')
            args=(
                '-layout' 'fi'
                # '-variant' 'mac'
            )
            ;;
    esac

    [ "${args:-}" ] || return 0

    echo "[$name]"
    echo setxkbmap -device "$id" "${args[@]}"
    setxkbmap -device "$id" "${args[@]}"
}

init_env

while read -r type id name; do
  [ "$type" == keyboard ] && apply_keymap "$id" "$name"
done <<< "$(parse_xinput_devices)"
