#!/bin/bash

device=$1
shift
args=("$@")

brightnessctl \
  --quiet \
  --min-value=1 \
  --device "$device" \
  "${args[@]}"

cur=$(brightnessctl -d "$device" get)
max=$(brightnessctl -d "$device" max)

echo $[100 * $cur / $max ]
