#!/bin/bash

d=/sys/class/backlight/intel_backlight

function usage()
{
    echo "usage: ${0##*/} [ min | max | [+|-]<value> ]"
}

function get_brightness()
{
    echo $(<${d}/brightness)
}

function get_max_brightness()
{
    echo $(<${d}/max_brightness)
}

function set_brightness()
{
    local value=$1
    sudo tee ${d}/brightness >/dev/null <<<"$value"
}

value=$1

case "${value}" in
    -h|--help)
        usage
        ;;
    '')
        get_brightness
        ;;
    [+-]*)
        set_brightness $(($(get_brightness) + value))
        ;;
    min)
        set_brightness 0
        ;;
    max)
        set_brightness $(get_max_brightness)
        ;;
    *)
        set_brightness ${value}
        ;;
esac
