#!/bin/bash

DIRS=( ~/m ~/mmgw-sw )
IGNORE="not implemented yet"

TIMEFORMAT="took: %1lR"

SUBDIRS=
for dir in ${DIRS[@]}; do
    for subdir in $dir/*; do
        SUBDIRS+=("$subdir")
    done
done

COUNT=${#SUBDIRS[@]}
for ((i=1; i<=${COUNT}; i++)); do
    subdir=${SUBDIRS[$i]}
    s=${subdir##*/}
    dir=${subdir%/*}
    d=${dir##*/}
    tag=$d-$s.tags
    tagf=~/.vim/tags/$tag

    echo "($[$i+1]/${COUNT}) building $tag"
    ctags \
        -R \
        --exclude="*.strip.pl" \
        -f $tagf \
        $subdir
done
