#!/bin/bash

ctags -R -f ~/.vim/tags/efl.tags \
	/usr/include/Imlib2.h \
	/usr/include/Eet.h \
	/usr/include/Evas*.h \
	/usr/include/Ecore*.h \
	/usr/include/Edje*.h \
	/usr/include/Embryo.h \
	/usr/include/Epsilon* \
	/usr/include/Etk_Engine_Ecore_Evas*.h \
	/usr/include/Emotion.h \
	/usr/include/ewl \
	/usr/include/etk \
	/usr/include/efreet \
	/usr/include/eina*
