#!/bin/bash
#
# diff checked out clearcase files

[ -z "$1" ] && echo "usage: $0 <path...>" && exit 1

DIFF=diff

[ -t 1 ] && which colordiff &>/dev/null && DIFF=colordiff

ctfiles "$@" | while read f; do
    $DIFF -u "$f@@/main/LATEST" "$f"
done
