#!/bin/bash
#
# usage: ctdiff [ -b branch | -t TAG ] [ -r ] <path...>

for p in "$@"; do
    cleartool lsco -s -me -r $p |
        while read f; do
            diff -u $f{@@/main/LATEST,}
        done
done

