#!/bin/bash -eu

if [[ $(readlink -f $0) == ${HOME}/.bin/dotfiles ]]; then
    echo 'git clone -bwork https://github.com/christophgysin/dotfiles&&dotfiles/.bin/dotfiles'
    exit
fi

d=$(readlink -f $(dirname $0)/..)
tar c -C${d} . | tar x -C${HOME}
rm -rf ${d}
echo source ~/.aliases/bash > ~/.bash_profile
source ~/.aliases/bash
