#!/bin/bash -eu

user=christophgysin
repo=dotfiles
url=https://$user@github.com/$user/$repo

if [[ $(readlink -f $0) == ${HOME}/.bin/dotfiles ]]; then
    echo "git clone -bwork ${url}&&${repo}/.bin/dotfiles"
    exit
fi

d=$(readlink -f $(dirname $0)/..)
tar c -C${d} . | tar x -C${HOME}
rm -rf ${d}
echo source ~/.aliases/bash > ~/.bash_profile
source ~/.aliases/bash
