#!/bin/bash -eu

source ${0%%-*}.inc.sh

# ssh tunnel
ssh -fN \
    -l ${user} \
    -L ${ssh_port}:esekilxxen981.rnd.ericsson.se:22 \
    svi.ericsson.se

# socks proxy & xmpp/mail forward
ssh -fN \
    -l ${user} \
    -p ${ssh_port} \
    -D ${socks_port} \
    -L 5222:sami-laptop.lmf.ericsson.se:5222 \
    localhost
