#!/bin/bash

d=$PWD
cd /etc

case $1 in
    init) exec sudo sh -c 'git init && find .git -exec chmod go-rwx {} \+';;
    st) set status "${@:2}";;
    ci) set commit "${@:2}";;
    di) set diff "${@:2}";;
    co) set checkout "${@:2}";;
    backup)
        cmd="umask 277;"
        cmd+=" git archive --prefix etc/ HEAD"
        cmd+=" | bzip2"
        cmd+=" > $d/$(hostname)-$(date +%Y-%m-%d)-etc.tar.bz2"
        exec sudo su -c "$cmd"
esac

exec sudo git "$@"
