#!/usr/bin/env bash

DEVICE=/dev/video6

usage() {
  echo >&2 "Usage: $0 [ c(apture) | p(review) ]"
  exit 1
}

capture() {
  gphoto2 \
    --quiet \
    --stdout \
    --capture-movie \
    | gst-launch-1.0 \
      --quiet \
      --no-position \
      fdsrc fd=0 \
      ! decodebin \
      ! videoconvert \
      ! v4l2sink device=$DEVICE
}

preview() {
  mpv \
    --no-cache \
    --untimed \
    --no-demuxer-thread \
    --video-sync=audio \
    --vd-lavc-threads=1 \
    --vf=hflip \
    av://v4l2:/$DEVICE \
    "$@"
}

action=${1:-capture}
shift

case $action in
  p*)
    preview "$@"
    ;;
  c*)
    capture "$@"
    ;;
  *)
    usage
    ;;
esac
