#!/bin/bash

now=$(date -d "now" +%s)
yellow="\033[01;33m"
white="\033[01;37m"
reset="\033[01;00m"

first=0
while read TIME LINE; do
    time_s=$(date -d ${TIME} +%s)
    if [ $[ ${now} + 5*60 ] -lt ${time_s} ]; then
        if [ ${first} -eq 0 ]; then
            echo -en "${yellow}"
        else
            echo -en "${white}"
        fi
        left=" ${reset}"

        first=1
        mins=$[ ( ${time_s} - ${now} ) / 60 ]
        hours=$[ mins / 60 ]
        mins=$[ mins % 60 ]

        if [ ${hours} -gt 0 ]; then
            mins=$[ mins + 100 ]
            left+="(${hours}:${mins:1})"
        else
            left+="(${mins} mins)"
        fi
    fi
    echo -n ${TIME} ${LINE}
    echo -ne "${left}"
    echo -ne "${reset}"
    echo
done < $(dirname $0)/hsl-timetable
