#!/bin/bash

NAME=$1

if [ -z $NAME ]; then
	echo "usage: $(basename $0) <class name>"
	exit 1
fi

if [ -e $NAME.h ]; then
	echo "file $NAME.h exists! aborting"
	exit 1
fi
if [ -e $NAME.cpp ]; then
	echo "file $NAME.cpp exists! aborting"
	exit 1
fi

BASENAME=$(basename $NAME)
NAME_UPPER=$(echo $BASENAME | awk '{print(toupper($1))}')

cat > $NAME.h << EOF
#ifndef ${NAME_UPPER}_H
#define ${NAME_UPPER}_H

//#include <>

class ${BASENAME}
{
public:
	${BASENAME}();
	~${BASENAME}();

private:

};

#endif /* ${NAME_UPPER}_H */
EOF


cat > ${NAME}.cpp << EOF
//#include <>

#include "${BASENAME}.h"

${BASENAME}::${BASENAME}()
{
}

${BASENAME}::~${BASENAME}()
{
}
EOF
