#!/bin/bash

int=eDP-1
ext=DP-2
vga=HDMI-1
pos=right-of

case ${1} in
    int)
        xrandr \
            --output $int --auto \
            --output $ext --off \
            --output $vga --off \
            ;;
    ext)
        xrandr \
            --output $int --off \
            --output $ext --auto \
            --output $vga --off \
            ;;
    dup)
        xrandr \
            --output $int --auto \
            --output $ext --auto --same-as $int \
            --output $vga --off \
            ;;
    dual)
        xrandr \
            --output $int --auto \
            --output $ext --auto --$pos $int \
            --output $vga --off \
            ;;
    above)
        xrandr \
            --output $int --auto --pos 640x1600 \
            --output $ext --auto --pos 0x0 \
            --output $vga --off \
            ;;
    vga)
        xrandr \
            --output $int --auto --primary \
            --output $ext --off \
            --output $vga --auto --above $int \
            ;;
    projector)
        xrandr \
            --output $int --off \
            --output $ext --off \
            --output $vga --auto \
            ;;
    all)
        xrandr \
            --output $int --auto \
            --output $ext --$pos $int --primary \
            --output $vga --above $ext \
            ;;
    *)
        echo "usage: $(basename "$0") [ int | ext | dup | dual | above | vga | projector | all ]";
        exit 1;;
esac
