#!/bin/bash

[ $(id -u) = 0 ] || SUDO=sudo

config_dirs=(
    /etc
    /boot
    /usr
    /var
)

$SUDO \
    find "${config_dirs[@]}" \
        -name "*.pacnew" \
        -exec pacnew-update-1 '{}' ';'
