#!/bin/bash

EDITOR=${EDITOR:-vim}
which colordiff &>/dev/null && DIFF="colordiff -up"
DIFF=${DIFF:-"diff -up"}
MERGE="vimdiff"

new=$1
[ "${new##*.}" != "pacnew" ] && echo "usage: $0 </etc/file.pacnew>" && exit 1
old=${new%.pacnew}

while true; do

    $DIFF "$old" "$new"

    if diff -q "$old" "$new" >/dev/null; then
        rm "$new" && break
    else
        echo "Files $old and $new differ. Do you want to:"
        echo " k) keep old $old, delete new $new?"
        echo " u) use new $new, delete old $old?"
        echo " o) edit old $old?"
        echo " n) edit new $new?"
        echo " m) merge both?"
        echo " s) skip this file, do nothing?"
        echo " q) quit processing (kill parent)?"
        echo
        echo -n "Choice (k/u/o/n/m/s/q)? "; read CHOICE

        case "$CHOICE" in
            k) rm "$new" && break;;
            u) mv "$new" "$old" && break;;
            o) $EDITOR $old;;
            n) $EDITOR $new;;
            m) $MERGE $old $new;;
            s) break;;
            q) kill $PPID; break;;
            *) echo "invalid choice!";;
        esac
    fi
done
