#!/usr/bin/env bash
set -euo pipefail

# cans
#QC35_ADDRESS=04:52:C7:C6:77:0F
# silver
QC35_ADDRESS=04:52:C7:34:F5:90

action=${1:-status}
shift || :

based() {
    based-connect $QC35_ADDRESS "$@" || true
}

case $action in
    connect)
      bluetoothctl connect $QC35_ADDRESS
      ;;
    status)
        based -d
        sleep 0.01
        bat=$(based -b)
        echo "Battery: $bat%"
        sleep 0.01
        based -a
        ;;
    fw)
        based -f
        ;;
    serial)
        based -s
        ;;
    bat)
        based -b
        ;;
    connected)
        based -a
        ;;
    connect)
        based --connect-device "$@"
        ;;
    disconnect)
        based --disconnect-device "$@"
        ;;
    nc)
        if [ $# -ne 1 ]; then
            echo >&2 "usage: $0 nc [ high | low | off ]"
            exit 1
        fi
        based -c "$1"
        ;;
    raw)
        based "$@"
        ;;
    *)
        echo "usage: $0 [status | bat | nc]"
        ;;
esac
