#!/usr/bin/env python

import sys
import boto3

args = sys.argv[1:]
bucket_name = args[0]

print("Deleting bucket! Are you sure? (Ctrl-C to abort) ")
input()

s3 = boto3.resource('s3')
bucket = s3.Bucket(bucket_name)
bucket.object_versions.delete()
bucket.delete()
