#!/bin/bash
set -euo pipefail

file=~/.i3lock_screen_locked.png

scrot --silent --overwrite $file
convert -scale 10% -scale 1000% $file $file
i3lock --image $file #--ignore-empty-password
sleep 0.5
xset dpms force off
