#!/usr/bin/env bash

xinput --map-to-output "Wacom Pen and multitouch sensor Pen eraser" "eDP-1" --scale 0.5
xinput --map-to-output "Wacom Pen and multitouch sensor Pen stylus" "eDP-1" --scale 0.5
xinput --map-to-output "Wacom Pen and multitouch sensor Finger touch" "eDP-1" --scale 0.5
