#!/bin/bash
#
# increase pulseaudio volume beyond 153%

dump=$(pacmd dump)

read _ sink < <(grep ^set-default-sink <<< $dump)
read _ source < <(grep ^set-default-source <<< $dump)
read _ _ volume < <(grep -m1 "^set-sink-volume $sink" <<< $dump)
read _ _ sink_mute < <(grep -m1 "^set-sink-mute $sink" <<< $dump)
read _ _ source_mute < <(grep -m1 "^set-source-mute $source" <<< $dump)

step=3

case ${1} in
    up)
        pacmd set-sink-volume "$sink" $(( volume + step * 0x10000 / 100 ));;
    down)
        pacmd set-sink-volume "$sink" $(( volume - step * 0x10000 / 100 ));;
    [-+][0-9]*|[0-9]*)
        pacmd set-sink-volume "$sink" $(( volume + $1 * 0x10000 / 100 ));;
    mute)
        pacmd set-sink-mute "$sink" yes
        ;;
    unmute)
        pacmd set-sink-mute "$sink" no
        ;;
    toggle-mute)
        [ $sink_mute == yes ] && "$0" unmute || "$0" mute;;
    mic-mute)
        pacmd set-source-mute "$source" yes
        ;;
    mic-unmute)
        pacmd set-source-mute "$source" no
        ;;
    mic-toggle-mute)
        [ $source_mute == yes ] && "$0" mic-unmute || "$0" mic-mute;;
    *)
        echo "usage: $0 <up|down|[+]n|-n|mute|unmute|toggle-mute>"
        exit 1;;
esac
