#!/usr/bin/env bash
set -euo pipefail

action=${1:-}

case $action in
  on)
    sudo systemctl start openvpn-client@protonvpn
    ;;
  off)
    sudo systemctl stop openvpn-client@protonvpn
    ;;
  toggle)
    [ -d /proc/sys/net/ipv4/conf/tun0 ] && $0 off || $0 on
    ;;
  status)
    sudo systemctl status openvpn-client@protonvpn
    ;;
  *)
    echo "Usage: vpn <on|off|toggle|status>"
    ;;
esac
